### ISSUE TITLE
Replaced deprecated module gulp-util

### ISSUE THREAD

**Issue by jared-thompson** [AlbertoElias/gulp-lintspaces#13]
gulp-utils has [been deprecated](https://github.com/gulpjs/gulp-util)
And it breaks [gulp version 4](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5).

Replace `gutil.PluginError` with [`plugin-error`](https://www.npmjs.com/package/plugin-error).

**Comment by AlbertoElias** [comment]
Would you mind filing a pr? Thanks!

**Comment by AlbertoElias** [comment]
Fixed in #14
