### ISSUE TITLE
gulp-lintspaces affected by cryptominer hijacker inserted into event-stream

### ISSUE THREAD

**Issue by Anthony-Mckale** [AlbertoElias/gulp-lintspaces#15]
https://github.com/dominictarr/event-stream/issues/116

recommended solutions are to update "event-stream@4.0.1" or downgrade to "event-stream@3.3.4"

think event-stream@3.3.6 is the hijacked version

**Comment by Anthony-Mckale** [comment]
ps for anyone affected these command line commands will clear your cache and re-download new dependencies, since the bad package is removed from npm it'll download a non bad version of the package

you should be aware this will delete your package locks, you can also manually update package-lock.json to change the event-stream version

```
npm cache clean --force
rmdir /S node_modules
rm package-lock.json

npm install
```

**Comment by AlbertoElias** [comment]
This is now fixed, sorry about the delay
