### ISSUE TITLE
.editorconfig option not working

### ISSUE THREAD

**Issue by localjo** [AlbertoElias/gulp-lintspaces#4]
I may be using this wrong, but I'm not getting any output from the linting.

Here's my gulp task;

```
gulp.task('lint', function() {
  return gulp.src('assets/scripts/**/*')
    .pipe(lintspaces({
      editorconfig: '.editorconfig'
    }))
    .pipe(lintspaces.reporter());
});
```

My files have obvious whitespace violations but when I run this task, I get the following output;

```
[21:57:53] Starting 'lint'...
[21:57:57] Finished 'lint' after 3.73 s
```

Any ideas?

**Comment by josiahsprague** [comment]
I tried adding a `console.log('reporting')` line as the first line in the reporter function, and nothing gets logged.

**Comment by localjo** [comment]
I tried logging `file.lintspaces` from inside the reporter function on line 32, and it logs an empty object `{}`. So maybe the problem is either that not all of the files are being picked up, or that the correct linting rules aren't being applied.

**Comment by localjo** [comment]
Passing in an options object works fine, but I've tried two different versions of `.editorconfig`;

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
```

And just

```
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
```

I'll continue experimenting with other options.

**Comment by josiahsprague** [comment]
I don't see the string "editorconfig" anywhere in the code base other than the README. Is this feature still a thing?

**Comment by localjo** [comment]
Seems that this is an issue with node-lintspaces. Moving over there.
