### ISSUE TITLE
Linting stops on first file with errors

### ISSUE THREAD

**Issue by localjo** [AlbertoElias/gulp-lintspaces#5]
If I am trying to lint a whole directory of files, after the first file with linting errors is encountered the linting function stops, and the remaining files don't get linted. I'd rather be able to lint all of the files at once and get a full list of linting errors. I think the issue is the way errors are emitted on [this line](https://github.com/AlbertoElias/gulp-lintspaces/blob/master/index.js#L49). The code should probably wait until all files are linted before emitting errors.

**Comment by AlbertoElias** [comment]
#8 released in v0.4.0
