### ISSUE TITLE
add option failOnError and failAfterError for comfortable run tasks in gulp on CI

### ISSUE THREAD

**Issue by alexander-akait** [AlbertoElias/gulp-lintspaces#6]
https://github.com/adametry/gulp-eslint#eslintfailonerror
https://github.com/adametry/gulp-eslint#eslintfailaftererror

**Comment by localjo** [comment]
PR #8 may solve your issue. I haven't heard from @AlbertoElias in a week and a half, so I'm not sure if that PR will get merged any time soon or not.

**Comment by alexander-akait** [comment]
@AlbertoElias bump
